### ISSUE TITLE
Provide support for ember data

### ISSUE THREAD

**Issue by crodriguez1a** [crodriguez1a/ember-sort-filter-table#19]
Maybe something like `{{sf-table store=myEmberDataThing}}`

**Comment by crodriguez1a** [comment]
- [x] Ember data block support and partial inline support (completed #28 )
- [ ] Ember data inline support

**Comment by mehulkar** [comment]
hey! just tried this out and it looks like there isn't a way to only make tables with a subset of `DS.attr` properties on a model? Maybe I am using it wrong?

E.g. in your demo code, if `model` has more properties than the ones specified in `sf-headings`, they are also included in the table. I can map over my data, but at that point, I don't need to use the Ember data feature.

**Comment by crodriguez1a** [comment]
@mehulkar Thanks for pointing this out. I did discover this over the weekend. I'm working out a solution whereas sf-headings will define the subset to display. Also, we I want to make sure that the private properties can also be defined in sf-headings for filtering only (just like the pojo implementation). Would you mind opening an issue including your description and assign to me?

**Comment by mehulkar** [comment]
filed #29! thanks :)
