### ISSUE TITLE
DS Model properties are not filterable

### ISSUE THREAD

**Issue by mehulkar** [crodriguez1a/ember-sort-filter-table#29]
hey! just tried this out and it looks like there isn't a way to only make tables with a subset of DS.attr properties on a model. 

E.g. in your demo code, if model has more properties than the ones specified in sf-headings, they are also included in the table. I can map over my data, but at that point, I don't need to use the Ember data feature.

**Comment by mehulkar** [comment]
PS, it turns out that this actually wasn't a good fit for what I needed (wanted to customize the edit UI and render components for each row also), so I decided not to use this for now. Just filing this because you asked me to! 

Thanks for such a quick response though! I'm definitely going to remember this addon for simpler table rendering in the future :)

**Comment by crodriguez1a** [comment]
@mehulkar FYI, I finally got around to fixing this. It'll go in the next release. Thanks for pointing this out.

**Comment by crodriguez1a** [comment]
@mehulkar FYI, I know you found another solution, but should be closed when #30 lands.

**Comment by mehulkar** [comment]
awesome!
