### ISSUE TITLE
sf.data has empty row set although data is retrieved

### ISSUE THREAD

**Issue by CrushedPixel** [crodriguez1a/ember-sort-filter-table#42]
I have the following setup:

my-component.hbs
```handlebars
{{#sf-table as | sf |}}
  <thead>
  <tr>
    {{sf.headings
      headings=(array
        (hash key="username" display="Username")
        (hash key="createdAt" display="Joined")
        (hash key="id" display="id")
      )}}
  </tr>
  </thead>
  <tr><td colspan="99">{{sf.filter placeholder="Search" withClearField=true}}</td></tr>
  <tbody>
  {{sf.data store=users}}
  </tbody>
{{/sf-table}}
```

my-component.js
```js
  store: Ember.inject.service(),

  users: Ember.computed(function() {
    return this.get('store').query('user', { active: true });
  }),
```

The server *does* return an array containing user objects, and I can use the users in for example an `each` helper, but the sf-table has no rows.

What am I doing wrong?

**Comment by crodriguez1a** [comment]
@CrushedPixel You may not be doing anything wrong. I'll write a test and see if I can replicate.

**Comment by crodriguez1a** [comment]
@CrushedPixel Okay, I think the problem here is that the `users` computed property is actually a returning a `PromiseArray`, and not a `RecordArray`. The add-on is not smart enough to interpret the Promise. I think if you were to load `users` in the route and pass it down to `my-component`, you would see the expected behavior.

`{{my-component users=model.users}}`

**Comment by CrushedPixel** [comment]
I've tested it as you said, but the code is still highly buggy.
Here are some of the flaws I found.

[sf-em-data.js#L31](https://github.com/crodriguez1a/ember-sort-filter-table/blob/master/addon/components/sf-em-data.js#L31):
```js
  _extractPojo(store) {
    return store.toArray().map((item) => get(item, '_internalModel._data'));
  },
```
should instead be `get(item, '_internalModel.__data')` (two underscores for `__data`).

In [`_filterByHeadings`](https://github.com/crodriguez1a/ember-sort-filter-table/blob/master/addon/components/sf-em-data.js#L46), I've found two issues:

```js
      // when headings and keys match, return early
      if (headings.length === keys(_obj).length) {
        return _obj
      }
``` 
this should actually compare the contents of the headings with the object keys, not only the length - they may contain completely different data.

Furthermore, the following `for` loop makes no sense:

```js
      for (let key in _obj) {
        if (!headings.includes(key)) {
          delete _obj[key]
          return _obj;
        }
      }
```
an object is only returned if it contains a key not present in `headings`. you should move the `return _obj` outside of the `for` loop.

Additionally, the object keys are never sorted to match the headings, which means that the data entries may be arranged in a completely different order than the headings suggest.

This definitely needs to be done in order to make the `sf-em-data` component usable.

**Comment by crodriguez1a** [comment]
@CrushedPixel Well, thanks for tearing this apart. It might be time to re-write the component/add-on (or let it go in favor of something that is regularly maintained). I've only had the time to work on it once this entire year, and certainly have not given it the attention required.

For the time being, let me know if you want to write some unit tests to address what you've mentioned above. I'll add you as a contributor.

**Comment by crodriguez1a** [comment]
@CrushedPixel Closing this issue. Feel free to add some unit tests to address some of the issues you saw. Thanks.
